/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardEmissionsRouteImport } from './routes/dashboard.emissions'
import { Route as DashboardLeakPointsRouteImport } from './routes/dashboard.leak-points'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSimulationsRouteImport } from './routes/dashboard.simulations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmissionsRoute = DashboardEmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeakPointsRoute = DashboardLeakPointsRouteImport.update({
  id: '/leak-points',
  path: '/leak-points',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationsRoute = DashboardSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/dashboard/emissions': typeof DashboardEmissionsRoute
  '/dashboard/leak-points': typeof DashboardLeakPointsRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/dashboard/emissions': typeof DashboardEmissionsRoute
  '/dashboard/leak-points': typeof DashboardLeakPointsRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/dashboard/emissions': typeof DashboardEmissionsRoute
  '/dashboard/leak-points': typeof DashboardLeakPointsRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/dashboard/emissions'
    | '/dashboard/leak-points'
    | '/dashboard/recommendations'
    | '/dashboard/settings'
    | '/dashboard/simulations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/dashboard/emissions'
    | '/dashboard/leak-points'
    | '/dashboard/recommendations'
    | '/dashboard/settings'
    | '/dashboard/simulations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/dashboard/emissions'
    | '/dashboard/leak-points'
    | '/dashboard/recommendations'
    | '/dashboard/settings'
    | '/dashboard/simulations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/emissions': {
      id: '/dashboard/emissions'
      path: '/emissions'
      fullPath: '/dashboard/emissions'
      preLoaderRoute: typeof DashboardEmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leak-points': {
      id: '/dashboard/leak-points'
      path: '/leak-points'
      fullPath: '/dashboard/leak-points'
      preLoaderRoute: typeof DashboardLeakPointsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulations': {
      id: '/dashboard/simulations'
      path: '/simulations'
      fullPath: '/dashboard/simulations'
      preLoaderRoute: typeof DashboardSimulationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEmissionsRoute: typeof DashboardEmissionsRoute
  DashboardLeakPointsRoute: typeof DashboardLeakPointsRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulationsRoute: typeof DashboardSimulationsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEmissionsRoute: DashboardEmissionsRoute,
  DashboardLeakPointsRoute: DashboardLeakPointsRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulationsRoute: DashboardSimulationsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
